apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-declarative
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: dejanu/python_hello:1.1
        ports:
        - containerPort: 5555
